language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: kmuLJjMRSdGLlaZzRRjc1rtod2LCXTkMbzLXp4JIBAwnpi2jgKctVEamsEHjz4GTL6yavlz8nqOsVYZJxW9skTN13x4W8RQ+dIBqLBi5FaNROltEP6KgNBlXnm6AZ3DuoY2RnVUAwbIn63cGcUeAeF+2V5gNzPqzJ1UXUUxbdkL9qprgPKfHoL6BJXcDWch3+o7FtmDNIR2dOxELOo34PSBpI0YZtNSau5Jf1UlBB2lycHfO/yKbqCC9WkhgJdniXaCkA0xJIrxGrKolJjnEH2juJfdd57r2BdwTW+Ra9KngibtGN0Emww0VIZSuyHPZ/bcOWXyTQ8qlQpg6CzIrRUCCgRRAaVSCyq5GavPUg1kVgDSL20rwMRVArp/DZLgn6a9IeZUCycqTdusXChq5T3tTtcreFvDdgvdFICSZIAvVkQXjBeCsRIYGjo+QcFDehrEQmuVCHSx8GGPy5UPWJ0vI2LuHGJhm3qz1cCHFa8GPFGPlKv7Cm47aUYKixuu4eBTeNa2rjQYBJSx4mw1lv8qMWfJp0nMx1OL3E/o99DNkn/zHjHHbdqtLp5P52qVXQGhgjrXhk/p8OhuNXm7vwLGR0b7goNfhvEVp+5sZpvUx+eDdW1mfeq8PgQedwXyHYdm9YiqCMzSXTOpAodi9aCs4t21hUdW3qdWw2Kgporw=
  - secure: YtODFjoA7KA2A6PvyryKT4axD8klEehpxABxaLT+1rb7UIZ7wxrp1wzwI280lWxpbFfYWggG7AIz2wf4+8Tge1xEND0SiCWy/BQrfyov3nUb2plxbGnpL8m5/LMNfRmYWcmTs4Q3rVjyxOBJqAzm65kf3epUG+iKfINRHQmJmv1EHhPEK8a1Od6qSBi9W+DHLI7Am+f503rvPOWWy50FtJ5gVb4XpphJoLmyScvV2ti5x32I7MlaN7FpumFhWp0oafvHCtNTHk0J+zwVD5/c/dXxthV57IOBdaCrqcb54qhtvhUXyECzQwJn1Kf6m8bDHYbzq/kNqglMxFCsiajSEO7zmOF5OGtiQ5/cftwupQl7goFsrr0JLROkGOTkdd+Q/qCbB4jBBrBvFsiL7ivC199dTsF7YtlHrTiYeFdntyazAa4eXyPJZqKKH4Jzw5OOD4G8qcI/OJBUj5Lq/RJnHG9IJ1RQijdBCCZx7VeOflzK24cLbtyiBujYC3zmucFgji2fMuFSxH4SZzYyn2oOxjtuzm98r/3DQMeddfRPp8fZFT8F5So2wUZW9WrA3UJTFJxczZ5+FISKhnyP7jTgNy/yayh+Xjkf/WqOAKjYfNf0zSKPRrn2KJvQORyBRfoXLzGgNIAv0alg0I7S4WrsGImA4P8NpMcVzpqLhMoUDTQ=
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- mvn clean package docker:build
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push drugotosto84/tmx-licensing-service:$BUILD_NAME
- docker push drugotosto84/tmx-organization-service:$BUILD_NAME
- docker push drugotosto84/tmx-confsvr:$BUILD_NAME
- docker push drugotosto84/tmx-eurekasvr:$BUILD_NAME
