language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export DOCKER_USERNAME="drugotosto84"
- export DOCKER_PASSWORD="UfhA2ybn"
script:
#- sh travis_scripts/tag_build.sh
#- sh travis_scripts/build_services.sh
#- sh travis_scripts/deploy_to_docker_hub.sh

before_deploy:
  # Set up git user name and tag this commit
  - export GIT_TAG=$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)
  - git config --local user.name "drugotosto"
  - git config --local user.email "ferrero.maurizio84@gmail.com"
  - git tag $GIT_TAG
  - git push origin $GIT_TAG

deploy:
  provider: releases
  api_key:
    secure: LHqZyI/0v46dl0b3LVJyYEYlbELVYLs6pSZnY0K9WuhlwlcoLunAkVogrLRhtMRaf4JybDhTmLgUggQVbm/4NYsEk//8keHwzMbNLyxQD4neMAn4D5KojG3HhF/uKaBFAgo7pzaBrp3dbi41gBqyjowoHyvLEA52V9MkG+7PJoQTchq/CN2/71OjKVP0ckr3znMd+Kg+KjczXz9ugECHLlatMp3JoN7yiTSJJ1IelPbSxJn8EBAtFJA3FiNS50C0oYUxMlI4mB8AGwB4Dnw9XgdSzwO/YHKFsWsntz0zkEp1ChCPzVsqqsjogG8C+WgWtmp6UzWmumwh8CB07ItUnXghVBFwaxIuU0ExHq5PIm8OW2axA52Pv66kmlBxc/gN5a1Uq0qGnBlTnNfzL7G/VHUzmlUcAkErXC/zlfdLYO7eItSE0aQMpbpnHdAr+1UWYVaordNAUcg8sdb8n1D8CnFE76qDJMUiOVaLejqrmayTXDX4Q778+0ccdLStqk++qLmHKhY7gOM+QGsd2UVwN/ZrBlTcz8fDYYX7ROOWP3eZVwl/t5tdCgyAwHbP/vhTG1X0glSGZHKoI6YJ7TAQXXPhnLe1B3p3aazCHUQqNiejOoFAgjwWb96MpUXI022E/CckiE3edFbohMSJBOxrOIGEK6hwPm3jxo4bV6/afAg=
  file: ''
  skip_cleanup: true
  on:
    repo: drugotosto/spmia-chapter4
    tags: true
