language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export DOCKER_USERNAME="drugotosto84"
- export DOCKER_PASSWORD="UfhA2ybn"
script:
- sh travis_scripts/tag_build.sh
env:
  global:
    secure: Jmv0+lA4k+jb0WY0bC/eLh4MDenjg3SUAs5T5R7KdKZh9KaULpoSrSxfDyvbsod7gv9j+FJMWJwl3+3Gouy1cSh+4ZjUpT2+C6PlnOTQE99t5Bwd2pumjqFPw70zMjsGMa29WSsxzEYwEYrZkLWhvFMLk/w+wXIdETPE45p/wQHB74VM8g3L8qE/fDeTezJ70vks4f0Ekx566XNsgTCy4SYYahsIk3xM1BylUEqc/Lu/CgOoFjZUOKf++/EI3jV2PcNd0oMgzXFoqWcr4Nwihwm1bJj1Gp6gFc9ZLElbdmdqGYP15sMyeeQFKgpUfGLHeOuyoDL9VtyhE/kqJNgHPanZpB+MBiZNtoVNyqs2GfYR8OWBWpv0lc3uj9Ione0QnFxflXU1OsV+sTI/XMFTGKD2cbomRwkBrTEHHldqDGEsVLfBDEjksxTshFLx1/Z/j6QOfcgqwC0aP84ZQa4K0RMvWs0Rz1L29bVzWX4rlDIEMYDAabygmpl1mNE6nxXhFLUStl9M5f22BbnqbZSK1x33Nlt5feH9Cd4hhpWSxHDLPrQcoz66zBaJ6SlMc3sZApsDKUfeqkyLalhn0hCbc5bnAdoNAEjo2K6IT61UtNj7v7+ZgsIsrq97CLehwFK3OelnxRqvQ5Y1vfbeX791oiQYpGA0QpjexvWnrpQ7BR8=
