language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export DOCKER_USERNAME="drugotosto84"
- export DOCKER_PASSWORD="UfhA2ybn"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
    secure: rJLdRRgW/2oYR5Cxasx2qlyj4r7daIakutmcBMIYfPBHEFzQX+LcoyW99RDLgX6mBL9ZutDYx83QmF+7GYTGxtUp48dHEylVeE3qEUdbYuyMGgANal6yBL8CYQ4CamlqgTDELRQL6wburhD6dWmk400ZwSHcKcgckV43zQd40OEBhehzI9idRXbzhksyaA6hKpAPJkEJFFVR/UgFrQeSpzAKBvhYgGRqQQv8fFGRrPwnaj10UHPmK6DW5hsA5tw3E4bkYU8/QgB16K0KY3X9uTpAeEXGsxIkYtNGUUf73iPD4giqTkgvklWSiivrUjvxHfxQ/0ivCmPj0IUwgiB1+OU+Y9lR2FtKXuvOX5JKbAzA4BaLuuvZ7F6FrhsYTrwymoGgWSPU7dIqaAHncT8+yKJpzh3xn/YtkXJOXNzFZD04nrkx8rAO8JGybE8rZrUB4ExfG2HLSSoKBnr7JJ30e+k5PIg1+zoJCsPiWS3PE0J2mpKgug96JE50916jscxn8DLpnUcIXa9k9iPUTogXqWs+joHP59gqtEh7PPpg7oUwwo31AJSxt/mO1iwUBsdIYrx1HMC5kn2bv8UNvNksy6WuJ70CS+oxIfD9taMBhUoqWzyGXbSOXFA6517mhOWoXiKIeRo7MfO+mq7Y2NE7+qXi810jr1tkx3AnX1auXqg=
