language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: B+8+Jd0asV+dFLLafvDsaCgzZMJTirjnTs9aIXyzPrFz8+hsUA24RB7hGKyxF0cVcxlY7/EtbaAQGN14MsnVuWM+pEwSr9L9iBW6axglZZsINeuNZFLYT7Y11uxY/YC7zpjug8t1IazNjAttefCDVhkEtj6D9bM5V9Po7e89o6y3jL67geX3w0Dt+wog0t2bHknk3rSFbFarba/J091Zcf+eKLml2zm6PdefSRTR0wXZVXeYw1JMFBZ/ITOWa25OyvMtofEC6G6wt6kpV/tw9+r/55CuVo7jvHWYXY9ysVCr8t5zeyI/yex2Aew3N9ZTk0EtSJ/71eTTORCFrM+j4AcvMYK7dADOCoo0tTBHxrAaB6Z9A3+jO4nX3WU5Nkpv7QC43MW7P+Sx4JUbM0SOCJDrglXRRNgd93HRbipHjiPRvWVNt7TXbLQ4twu+EJhmQ4/8yPbYuZS/EKEQIeIfPL3P1brqSxpj1tgCXr6daeaVKrcrSf9/x7PqaTU36zl3EYITcc4zmn15wUFA3BqIKXtMK0zaJ4MG+zcQlEOiV3HMKlyb9SPIy1wn6asARf8cAUGgtiEXZSHGgkc4iDpl4NWGGbCZ6DLoStWU400Pyz2ooePKbaUGSpk4C0uSOc4qVkgm2DdGot5huztUiVl14qRCXlp+/B1tqaVAXAOTQXU=
  - secure: QzIhS/M3wbKvm0UDd7eayK2QRjI0PlD2UqRid9tV/8Z9ZExNDhwqrqgBk/6GyJbG6GNtpuLB61O3EMV9db7hDuUDxHN+Q6hXanASohuu2BU5F99XxhJ1sLafA+5ZNVj9r5S9glqbm9GhdspY5NVFqB++Xe7E7iQL/n55Wpejg6zNF0/cEgJ8wo7rPRF1wet787amiETOzJhdAVOQhkTre9PfXnZqNYaFhND9jh/TMMBdmq78fn7LOuicwhLrVkcnMIG7/LI+hy7RaZu1KkWzzyn3gOsaM+FSJnr9GChcXyYNznBO1YOuyuCMm4rdYSczORNpHlHvINYhPmU5vB8zdqb4t+6KDYUZkJhKYFLAHMxFuNvGpPyVykf9Q0JFV5awguyivQh+aaBflT1qWUIjTh1i4ecKYuxxHDHWbAbyq1OMjtQGJxBDyY63XkdI74rR4Bq+2Ll9MFCkk/pXgT5gxEmAXxTYrY1WdeNSS++JH5fPtg2ZKLtft0/LtaKKe1a6q/nVlFSkz9Lx0a24L1AB3BgQ8hjO13xN47YuEBXsoaP2GICaif9RS9l5ofpwdfOkw5blI8g9DIaD4+c2n0NUmzXWNVZEVNfw4GKEbvR+eibVkNVdSXOtYCTlDK0UIxK/l2pBynL0JjSMNt/01o96JNEwQ1YdmTmO90mfGcGcb5E=
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push drugotosto/tmx-licensing-service:chapter4
- docker push drugotosto/tmx-organization-service:chapter4
- docker push drugotosto/tmx-confsvr:chapter4
- docker push drugotosto/tmx-eurekasvr:chapter4
