language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export DOCKER_USERNAME="drugotosto84"
- export DOCKER_PASSWORD="UfhA2ybn"
script:
- mvn clean package docker:build
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push drugotosto/tmx-licensing-service:$BUILD_NAME
- docker push drugotosto/tmx-organization-service:$BUILD_NAME
- docker push drugotosto/tmx-confsvr:$BUILD_NAME
- docker push drugotosto/tmx-eurekasvr:$BUILD_NAME
