language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: m/+loYIqaVIAfSzWV/oE9hyPM66orH851PEimKaXkLu+/yaNUIcJlQvKuSo63Xv19KBcPm1WYQE9MZ570MdtfpPeDuxePOVgc45P3Fc4kOiEGdJ07B/OG94mCawfO3HDkrBTUXLoLNx0JxFC0YaiQNimTSbG7xckONcguo7yWuhnG5TFZnEhC7syZIy56qrMRaz9F6W+NI+i52F1brl7v3wS2e8xZ1ikijcemylwBKYKkLZ40SuaB25reHBrDXwHYw1138xaMFQTQAJeNPQ6IOyeQtlE1VWoSjhRgcSudYvuh+S/go1kNpLOQLFFSLcIyS940hL3zf5JaKZ7HwsNZay/hpCgbHD2Ga3LLPTTYjnMUuE1Ii5j5wVm/ipUXkJBukDxl24g0BzPSEgztgLOWiaTzR5qj8hGreVNGe9aj/U+LTG1055knWug/2K8Dc6i8dI8qZO4aCLONWKI7biylmPI1dstCe2p6QxRhq047jypmEL9dUSY2W4v+eTKN+eVazTsS42Fs+P/coABUntFDT3woe1EBjV2x2wT3yX4gOXolm8xuABgtxQZ56Lrx5uV6ZDU9cmc7KC6ryIIooCsE3BHqGN++MeBoSJQROQfGLMFE7ZwzLki7OngUCxnlPwv0g6SP9Tom4/sWXePowIdYQMb6gdWEoozJfpRevODooY=
  - secure: GBzGtS8KLAr73cCnmkdxsoCkcCdTf2pfW2mjVSB2Xlfb39ZSdEwKvFTydQNzgFaD9rB1dGdIKE0zVNfXJKy66bruJk5MJkRvQbNXwzqF+r1kjBMIv1MNdOAzB1YOBn45JJVFgbaxVXgw6TrFMYeHmo8W9W4K3kMk+undREWvr1+6/aDSkRIo28u7NTp8vuqL8an/9yOGzO1vB3oSRur+FL1QQwEbrGchqJJ9N58BxZU7KH0/hLaqGLwocKAOdUeTFUNEaJdfOd/bu1vyHnYvYX+H0RbH2v74iK+6T3k3FuWtVPpEk0em/Y+S3t57BvGOcgVRp6Dd66IpAxzeZ1FUXcjO2bGI2w92TciYFRs2ewkZkRFVeTKARqM8ZCKciODXLSp0OFT+MgF5spWgPcTGgv5sSr1P4HHy7Z/qvem9Zmq/8Z4yU+k7ksKybBIoh9hxCuSk8KmtYZTf92MehgyzOm5XG9QRKHNzSmgON41+nwCSfIVhGPc0nQHZ55lpGrZWZnGUdMiQCVKkjkM4PfYPSMLayzub/gqAFnWVUSQhvlML/s/GARw1vK3MyU5WJ9/MaE7hJjucgjRxfZRbjGe9tsp91uToXVX8Oawu6DyVadX4LQSi4p8ODV29LV9zeT7d0VT2g6SUWODWGLrMaYk28L3ubXBuP7GluvW1F9MOKVs=
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
#- export DOCKER_USERNAME="drugotosto84"
#- export DOCKER_PASSWORD="UfhA2ybn"
script:
- mvn clean package docker:build
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push drugotosto84/tmx-licensing-service:$BUILD_NAME
- docker push drugotosto84/tmx-organization-service:$BUILD_NAME
- docker push drugotosto84/tmx-confsvr:$BUILD_NAME
- docker push drugotosto84/tmx-eurekasvr:$BUILD_NAME
