language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export DOCKER_USERNAME="drugotosto84"
- export DOCKER_PASSWORD="UfhA2ybn"
script: 
deploy:
  provider: releases
  api_key:
    secure: JMBXeat7Ob4df8SKfLBKHzkHH4xFIkckHnJSPM6wfLCNaTeFYMOtJ5VJsEYeqjeMLofwf/hAH80Yzz3lkokJ4z/eCUCm7V7Jn82NIhvNryxmraZ5sXy8emG8UpxdN3cjPm6UI8ZP8RSHMfpJxZa3zL1lPUwNNKQskQRTw1Gm4MepOS0DH6p4wwo4ZPuhDrUfuzk/yVCRMLxQhEeUrNZmdXNDImtR6y/2EYJ0VX0GWGbZzNwHoA4997/4fGHbVOvlwc+25D3tHjlgJJbVt2IukkgE/o2x/hdQ7dy8wIFvQOVuPxiJp3mqRWT8jhsvTgER4Kj98lnjJw01qIHvwMOg/wepH+mp6Pm3VJU4TpparhnZhPGH95y6xMFd/huZvbKHkr+u9vg0JhhjUFQXbrICIRl54+P+W/SiotFDckIFS4vcVeh4xTZWbGYAKn5xX00xB7e70EZsnh+o0QYIGqhTaTNX5sPSobR3e3ZoujJSU11TGwmWighEuDeviiWY2ZVlY94QRFGv1ImNTCeZr6gevp62lJEGLIx+o2NmyhTcH8W3wBqh8R8nUaxhKzuW1uWhb76OzAZaigLf8EqyAbAZ9LGdRJwsM1RZXv5aXFSaD2V2oGAeaGcaCsd7N+vRKwX0lsTqmDpJFVE3kowd/Ola+hy6ggBSf4rGewAGnbLlTJE=
  file: ''
