language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export DOCKER_USERNAME="drugotosto84"
- export DOCKER_PASSWORD="Juventus84"
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push drugotosto/tmx-licensing-service:chapter4
- docker push drugotosto/tmx-organization-service:chapter4
- docker push drugotosto/tmx-confsvr:chapter4
- docker push drugotosto/tmx-eurekasvr:chapter4
