language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- mvn clean package docker:build
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push drugotosto84/tmx-licensing-service:$BUILD_NAME
- docker push drugotosto84/tmx-organization-service:$BUILD_NAME
- docker push drugotosto84/tmx-confsvr:$BUILD_NAME
- docker push drugotosto84/tmx-eurekasvr:$BUILD_NAME
env:
  global:
  - secure: Bg8I/PWmB0bVSJ8B0ba50SLQKeCr3kI3gEVAeKLOCi8DvrJzVsYIXeCPdM6M7FWKiiJMXXFsmknrtouKnDlWvRx6oONglVGD38enSQ5Ytq4ewgzc/Qm+XXrt5nfdCfXQPnwYGWLPG4D03LKj58cXwBJhUzO0MMIVTSU+Uy2h1iFTBkv03OQsGz8k8YMUU7B1Svljxpc96hdCpKLrH9K2kGarRHSDf5LMVM9BEUJScJCSYYT6EPExk2ZGvcNux/sI94qmENEMd/kNu0GrH94OI6F/CSZEHkN4tEunCYll+2eZ9KcajcJRstx+gXkjEKc19qOAx3NPvejA8juwdxFJBJeCJICwbpznj8U/Ha/pTOm2jgCYyuLW/yoFRkNclpXlbLHu8J0P8LDViq4DRbzGmCGYCNdGS9nxf5e16O/c0XXxzkIw5bZJMR1k4bcTBAJ5KOIg1mLDacUfdKRADp4QwFLNH9+GDwdTixXg4SlXL+LZcv80erCEbItgx7lnLzDriWg7dnjjmsLws6TBX3Ts0wc5AklZhsRBsWJ1ab6FQqXOpUEuAOVa4ulBwC92kU4JN8l49YgrgXUIIe783wU2vHhtnp4xEJtL00riuK2PNC48cXw6VugMRjQr/QjCe7WbwHJmcPkT11WUeMFbGP09MvhqzuPUBoJeirzaIx/HLe0=
  - secure: D5VQQ8WICifUHnw3o4WI7nnlhc96dg4BH3WmRh2RuSCeA2bAYYhQUdZveruinjehq0B32nK9FHqKnLWjQDTYAg6kgYCmxJJrRnHuxoqfCZa7MHvx511o0QZzT7GGG3t5RzMJqWnPT/4r+wVY2YWhUDtBp53knlFTCHvQ0yDGLI+epoZXDOUqOo7ziBR8ScmQ5y80Vier5I88AeXpLdNZ2gEdPVDvNhEx8WFUryCXDMKB9qOGMqwt8PJY+9DZXFdqaERvDBZzU10bWRU5waH2tnnLDrYglPz1xnDDHXqhzjsOkVCT/rjs2Bs3ljVAKuSthrEbcX5IVfiyzC9srN/9Tp8x7NJCXP6RLwr10mFyzqKkZp9YWdcToEzNVrbgUt3w7MPNm+WoLyoNHhQdnIo5SST7iHCI8evxs+hJatKIrH4HBxn9C1hQRQkqFlkrFwndpTW6V9L+Jcv2qdddvWyTVsOUkhZddH7gDDaXBeiU2cSNsYfIapfTQNCNecXXk3EFjvflc+PaY0knJqzj4zgKP16EGgnGlgGQhqEcMmt6DtYP5J8WaAxaPkFhd/+an8uZJMyijSpRlpgA6eYvxkwjqOpgmfxBB1Hq7KZHIcMf7QCM2hrKCSAh+vzd2EhdIib5Oa3Dn0p4XJayv6gf1Q0jSULKfcoGxqvcBh8v+VTDVRU=
