language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export DOCKER_USERNAME="drugotosto84"
- export DOCKER_PASSWORD="UfhA2ybn"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
    secure: rGd6SdNBpKf9AuXx6VZfsjZomAn3uuianwMT10uJEB1oq2c6NAdJv7mMb4hXpKnQPHPJ1RaOE3iBF+DG1EKrpaC+YWyqzb+sqs+6GCopUT23iRmU7DfsWLrCQqqAj92wFL4LfxYmHwV5dnxjKNDZh1N/ugsrpjJcGHevCtSl4D0pmNGrRQQK5gfmIzMYOtEqR1BX41TDavd7lIgnFtGb+0Fw3fh2D2/eKDbWFdIOdgaRj2DEzJa8b7/LdsgBr3IR4lDPeFlMAUk2qLBIwIw+f2IQigaxmo3pXB3Y7WnK5QtMmOSylKY0QHtW6NTYR4EoiBoSojoVimtP07V4xwu7zN0xPjjjB704WqX6Cku1qcsjxLeylAg1KmDXrP3KrEPp6r2y4T4ayTWNrUTywWkAQNgL3gLgmL6SsUVBfeevDYV7jZHyMZR46oIGDmyhYXBaK4W6u0zkulMvYx8Ca9VuyA8DLF63cHcxjFoH8Z3uNYG8eTu4fbu7EQ19b8W4ESm7KDE2Dc76oHCKavxU2b8F/TExMmC9npfnrUumAd54sLetPxQ1bEcHzgozvM/YxjjnxoebO+SqRkfL4oHV2WEId/U/bRI4RoPZj6PeHlIo8UK2f+qIX2OBcZhdm1cSmCOQNSZYAeRBDPnyH9JI/1gmnC7VzrHlikj41jneE8tzBI0=
