language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: eYVnwK4QjXOOMZpyGUY5eC8jVREVzw9g9RZsTDHAcZwzZw5wCA6/qRV2QwIyfY6wp2L9JPBU8K/4jYkQu4DRl4LJlXweODIusXkqHBbzi+NZx6SKRvrmh7oK506FeYnd+yPWOksDqMMR3J0gs+CW+QtqwwhBuXxOjA29C3cQ91n1ON8Nms333VVipQ8z6WFm5NfJPR+lNWtMvcirFvQSrpDF9FYXWNKfR1tvWv4Tk8ORrURNT7DOQlggpN/bjTlpqXDc5rJzKqx8muaUm2+ZYPmh2lj5sk9oasyLYYShyMWEGH7WUyQY5E197x3s//gvgji3XzmQB5VGXPlaRDRTsFFCgSpw6SuMih0Xy0K6pEtNTNsPGARVjPFvbuPuBDR+GFDxsK4UujhfMH+/wplQflUkHc/fMAfRG+UrBPPKIAaJnbnYTIFvsqxcXbjWoVCgV95A2fP7OZLmraQSC2x18zQXcc2J1UhtvMygIGCAPwxyjqQNhWhne0CPqmfHC9f9/Dn4qGp401UR6dix8ghntPZTSoGQ+3OCUJBK5ufPCT29hsg7mSgl28UEjT+sFsLaF8sGJQHGNl0iB4rlv9QiyadOMYs4bOORxcmY+nTlMW5AHk2YTt0VIsDF7ORRS4yx/hn8v/JXE1JurTNwDMNyZPtXHYMZfr/fhoDInqKMZuc=
  - secure: PuL3pBLBpTaAuodOsQ17bwFA6ULCWfK5lP233qva2HDtA557jzbSqgpyC6H+B3+8eMpfj9QGMiiWDEhVa1YvGYdGRy/kXAbcmk8/mF/i9Aw3lv/i5dm3euuDQ77Y9Nm5jr6RZ6X80RfmM96C50/MW1L7b28kD1jWbzjLto6DeE+sshDMSRmuOpoLWyQcr9UeexHknqYoonaZ7vPEma0RpRNYnhyz0PPSCCfdyR9fQ0nfxsBphB3uG/yjwGjvKTB0n83wbu0PpkxRA0qwaZC84dlhj4YqX+2sJTAwpkdv5W6inSg56suzFuI0E4O7xqVEJQTH0LEsLgjgbr5fQGiVbrfGX3kc7aMUrjmvuxVxO7AtheHwKWz8quiDPdbBLBXnyoCNa8XoycbdH0bywdfhVMMRUXXm88rK87sN341l1aBZ80G3q71KrhtOIKdjtNSV2/cRyretJycVfDDkyMPWYGDY/Zg6hzdxjdlxQ78ELvY71JCXvLHq6UIhdki3/csf7IF/AB4yHxbJJkCy3AA/mFQamkU1ta65q4kDFMWaUO4W20doU36RNcpgaX7NJI1RoQqoCWqebzWnEymj+1PN4PAKN1XtVOQhFyo+q7h8rNQHNyZWMcdVs7X4nxAK1OnlxPK5g3bhfccMHnY8q3r9iw9mW7dgRJg7FRqX39eh2Ss=
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push drugotosto/tmx-licensing-service:chapter4
- docker push drugotosto/tmx-organization-service:chapter4
- docker push drugotosto/tmx-confsvr:chapter4
- docker push drugotosto/tmx-eurekasvr:chapter4
