language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ferrero.maurizio84@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export DOCKER_USERNAME="drugotosto84"
- export DOCKER_PASSWORD="UfhA2ybn"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
    secure: lAtoA8pPCK5oh45gp5Mlg0pmOeDKTzP66FuJWnsSJG6Q9iym2VKlWZnGgQbxAdrWA6QwwGT4VkNuAkyD5wb1tyu23DMlGPXCJYO8hYO5GSr5I+McxaeJ2l7Jj1X9WtItYxZZ4hwpt4ehJotYhHLJ5WD9ucb9v9PCV7NKeA++aIx5/0X6A63HlyvV56O/l1BcQxfXVzImJzCgAjy6U8qojFt/syHudh8BU/00lGsZbdCiRFqtjK8X5JmX2TrPoktYAZWziSqcpCEtms/8KG/zvVZ6peAG7AlIs5MvJi0F8KeuW5i8ZtLUmvR5t3d4wp9rb6JgEZoMkJYmS/hXKqVP3QYrotvoyLzQevAVLS0mWssOgX/QZ1FF0WhyyPDnxxqRdu49CDC0p9v5MSWLg3VpTrmPT1j6Y91RbygmDMmqGkjVIqBAMOlhOgQR60Xlp9CC79t+d5Po2G1fmLJs+E3yxvoUPb2O7Go0szysBBa5CuHbQh6m3AgMQNKW3vqONsqdvs5KcMD2IJ+0q1t06A6eEu4qbwwYrJYQ3VpF2Y/6PZbFzzJsqMsbPBoAm/+ZeNFFA/DDSzjF+99cR60KqESOl1/Kb2EhFfZT/qlz8rFUr6DVW2Zjedv6pb29ufkgMNeRbYYLmsAW26/5Pv+YWIlk17dxomnsdwtFRyphkPHnIWs=
